#121 Arreglo de endpoints
chalosalvador/titulacion-esfot-frontend pull request #129
Opened 2021-06-14 18:26 UTC by NicoleZambrano02

2021-06-14 18:52 UTC, KevinJ1998 requested changes

2021-06-14 18:52 UTC, KevinJ1998 commented on src/components/PlanForm.js
> +        await API.post(`/projects/${projects[0].id}/plan-sent`, dataToSent);
Quitar dataToSent

2021-06-17 22:19 UTC, KevinJ1998 approved these changes

2021-06-18 00:49 UTC, ChantalMorales approved these changes

2021-06-18 00:49 UTC, merged